name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install jupyter

      - name: List files in the repository
        run: ls -R

      - name: Run Jupyter Notebook tests
        run: jupyter nbconvert --to notebook --execute "ENSF 619 A1.ipynb"
